name: Go Static Checks
on: pull_request

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    needs: frontend
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Copy built frontend
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: frontend/dist
      - run: go generate ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true
          # Show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
